{
 "title": "FastStream Metrics",
 "description": "FastStream is a powerful and easy-to-use Python framework for building asynchronous services interacting with event streams such as Apache Kafka, RabbitMQ, NATS and Redis",
 "tags": [ "faststream" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "app_name", "label": "App Name", "query": { "query": "label_values(app_name)" } },
   { "name": "metrics_prefix", "label": "Metrics Prefix", "query": "faststream" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total messages published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\"} [$interval]))"
    }
   ]
  },
  {
   "title": "Total messages received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_total\"} [$interval]))"
    }
   ]
  },
  {
   "title": "Total messages processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"} [$interval]))"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\", status=\"success\"} [$interval])",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Publish average duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_sum\"} / {app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_count\"}",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Process average duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_sum\"} / {app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_count\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_exceptions_total\"} [$interval]))"
    }
   ]
  },
  {
   "title": "Process exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_exceptions_total\"} [$interval]))"
    }
   ]
  },
  {
   "title": "Messages in progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_in_process\"})"
    }
   ]
  },
  {
   "title": "Messages processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"acked\"} [$interval])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\"} [1m])",
     "legendFormat": "{{destination}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Process per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"} [1m])",
     "legendFormat": "{{handler}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Messages in process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_in_process\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish duration [PR 99]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_bucket\"} [1m])) by(destination, le))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Process duration [PR 99]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_bucket\"} [1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Received message size [PR 99]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_size_bytes_bucket\"} [1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percentages of processed message statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Percent of acked messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"acked\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of error messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"error\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of skipped messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"skipped\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of nacked messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"nacked\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of rejected messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"rejected\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\"})",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}